create table public.plans(id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,description text,price numeric(12,2) not null default 0,currency text not null default 'ZAR',interval text not null default 'month' check(interval in('month','year','one_time')),active boolean not null default true,created_at timestamptz not null default now());
create table public.subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,plan_id uuid not null references public.plans(id),status text not null default 'active',provider text,provider_reference text,starts_at timestamptz not null default now(),ends_at timestamptz,cancelled_at timestamptz,created_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id),subscription_id uuid references public.subscriptions(id),amount numeric(12,2) not null default 0,currency text not null default 'ZAR',provider text,provider_reference text unique,status text not null default 'pending',metadata jsonb not null default '{}',paid_at timestamptz,created_at timestamptz not null default now());
create table public.story_rights(id uuid primary key default gen_random_uuid(),story_id uuid not null references public.stories(id) on delete cascade,rights_holder text not null,license_type text not null,territory text not null default 'South Africa',valid_from date,valid_until date,restrictions text,consent_reference text,created_at timestamptz not null default now());
create table public.storyteller_verifications(id uuid primary key default gen_random_uuid(),storyteller_id uuid not null references public.storyteller_profiles(id) on delete cascade,verification_type text not null,reference text,verified_by uuid references public.profiles(id),status text not null default 'pending',notes text,verified_at timestamptz,created_at timestamptz not null default now());
create table public.consent_records(id uuid primary key default gen_random_uuid(),subject_type text not null,subject_id uuid not null,consent_type text not null,granted boolean not null,granted_by uuid references public.profiles(id),evidence_reference text,created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,body text not null,type text not null default 'system',read_at timestamptz,created_at timestamptz not null default now());

alter table public.plans enable row level security;alter table public.subscriptions enable row level security;alter table public.payments enable row level security;alter table public.story_rights enable row level security;alter table public.storyteller_verifications enable row level security;alter table public.consent_records enable row level security;alter table public.notifications enable row level security;
create policy plans_public on public.plans for select using(active=true or public.is_staff());create policy plans_staff on public.plans for all using(public.is_staff()) with check(public.is_staff());
create policy subscriptions_self on public.subscriptions for select using(user_id=auth.uid() or public.is_staff());create policy subscriptions_staff on public.subscriptions for all using(public.is_staff()) with check(public.is_staff());
create policy payments_self on public.payments for select using(user_id=auth.uid() or public.is_staff());create policy payments_staff on public.payments for all using(public.is_staff()) with check(public.is_staff());
create policy rights_public on public.story_rights for select using(public.is_staff() or exists(select 1 from public.stories s where s.id=story_id and s.status='published'));create policy rights_staff on public.story_rights for all using(public.is_staff()) with check(public.is_staff());
create policy verifications_owner on public.storyteller_verifications for select using(public.is_staff() or exists(select 1 from public.storyteller_profiles t where t.id=storyteller_id and t.user_id=auth.uid()));create policy verifications_staff on public.storyteller_verifications for all using(public.is_staff()) with check(public.is_staff());
create policy consent_self_or_staff on public.consent_records for select using(granted_by=auth.uid() or public.is_staff());create policy consent_staff on public.consent_records for all using(public.is_staff() or granted_by=auth.uid()) with check(public.is_staff() or granted_by=auth.uid());
create policy notifications_self on public.notifications for select using(user_id=auth.uid());create policy notifications_update on public.notifications for update using(user_id=auth.uid()) with check(user_id=auth.uid());create policy notifications_staff on public.notifications for all using(public.is_staff()) with check(public.is_staff());
create index subscriptions_user_idx on public.subscriptions(user_id,status);create index payments_user_idx on public.payments(user_id,created_at desc);create index notifications_user_idx on public.notifications(user_id,created_at desc);

insert into public.plans(code,name,description,price,currency,interval) values
('family_monthly','Family Monthly','Affordable household access to the DFC library and live circles.',49,'ZAR','month'),
('family_annual','Family Annual','Annual family membership at a lower effective monthly cost.',499,'ZAR','year'),
('school_basic','School Basic','Small-school access to DFC story collections.',1499,'ZAR','month'),
('sponsored_community','Sponsored Community','Institution-funded access for a community or ECD cohort.',0,'ZAR','one_time')
on conflict(code) do nothing;
